openapi: 3.0.1
info:
  title: Interactive API Docs
  description: Use the interactive documentation to explore the endpoints CDO has
    to offer
  contact:
    name: CDO TAC
    email: cdo.tac@cisco.com
  version: '1.0'
servers:
- url: https://edge.staging.cdo.cisco.com/api/platform/public-api
  description: Staging
- url: https://edge.scale.cdo.cisco.com/api/platform/public-api
  description: Scale
- url: https://edge.ci.cdo.cisco.com/api/platform/public-api
  description: CI